# Render Blueprint for Trendx
# This file configures your Render deployment

services:
  - type: web
    name: trendx
    env: node
    plan: starter # Change to 'free' or another plan as needed
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true # Render will generate a secure random value
      - key: DATABASE_URL
        fromDatabase:
          name: trendx-db
          property: connectionString
      - key: R2_ACCESS_KEY_ID
        sync: false # You'll need to set this manually
      - key: R2_SECRET_ACCESS_KEY
        sync: false # You'll need to set this manually
      - key: R2_BUCKET
        sync: false # You'll need to set this manually
      - key: R2_ENDPOINT
        sync: false # You'll need to set this manually
      - key: R2_PUBLIC_BASE
        sync: false # You'll need to set this manually
      - key: FRONTEND_URL
        sync: false # Set to your Cloudflare domain

databases:
  - name: trendx-db
    plan: starter # Change to 'free' or another plan as needed
    databaseName: trendx
    user: trendx
